week 4/auction/config/routes.rb
Rails.application.routes.draw do
  
  get '/', to: 'users#welcome'

  post '/login', to: 'users#login'

  get '/users/overview', to: 'users#overview'

  resources :users, only: [:destroy, :show, :new, :create] do
    resources :products, only: [:destroy, :show, :index, :create, :new]
  end

  resources :products, only: [:index, :show] do
    resources :bids, only: [:create]
  end


end

week 4/auction/app/models/bid.rb
class Bid < ActiveRecord::Base
	
	validates :ammount, presence: true

	belongs_to :product
	belongs_to :user

	
end

week 4/auction/app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user
	has_many :bids


	def valid_bid(bid, user_id)

		high_enough(bid) && valid_user(user_id)
	
	end

	def high_enough(bid)
		if self.bids.order(ammount: :desc).first
			if bid>self.bids.order(ammount: :desc).first.ammount && bid > self.minimum_price
				true
			else
				false
			end
		elsif bid > self.minimum_price
			true
		else
			false
		end
	end

	def valid_user(user_id)

		!(self.user_id == user_id)

	end

		


end

week 4/auction/app/models/user.rb
class User < ActiveRecord::Base
	VALID_EMAIL_REGEX = /([a-z]|\d)+\@[a-z]+\.[a-z]+/
	validates :email, presence: true, length: { maximum: 255 },
	                    format: { with: VALID_EMAIL_REGEX },
	                    uniqueness: { case_sensitive: false }
	VALID_NAME_REGEX = /[a-zA-Z]+/
	validates :name, presence: true, length: {maximum: 100},
						format: { with: VALID_NAME_REGEX}
					
	

	has_many :products
	has_many :bids
end

week 4/auction/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

week 4/auction/app/controllers/bids_controller.rb
class BidsController < ApplicationController

	def create
		
		product = Product.find(params[:product_id])
		bid = params[:bid][:ammount].to_f
		user = User.find(session[:user])
		if user && product.valid_bid(bid, user.id)
			
			product.bids.create(
				ammount: bid,
				user_id: session[:user]
				)
		end	
		
		redirect_to product_path(Product.find(params[:product_id]))
	
	end


end

week 4/auction/app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def show
		redirect_to user_path unless session[:user]
		@product = Product.find(params[:id])
		@current_bids = @product.bids.order(ammount: :asc)
		@bid = Bid.new
	end

	def create
		redirect_to user_path unless session[:user]
		user =  User.find(params[:user_id])
		
		user.products.create(
			title: params[:product][:title],
			description: params[:product][:description],
			minimum_price: params[:product][:minimum_price],
			deadline: params[:product][:deadline]
		)

		redirect_to user_path(user)
	end

	def destroy

	end

	def new
		redirect_to user_path unless session[:user]
		@user = User.find(params[:user_id])
		@product = Product.new
	end

	def index
		redirect_to user_path unless session[:user]
		unless params[:user_id]
			@products = Product.all 
		end

	end

end

week 4/auction/app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def welcome
		@user = User.new
		reset_session
	end

	def login
		#binding.pry
		if user = User.find_by('email = ?', params[:email])
			if user && user.password == params[:password]
				session[:user] = user.id
				redirect_to user_path(user)
		else
			flash[:notice] = "Password incorrect idiot"
			redirect_to '/'
		end
	else
		redirect_to new_user_path
	end
	
	end

	def show
		redirect_to user_path unless session[:user]
		@user =  User.find(params[:id])
		@products = @user.products
		
	end

	def create
		
		user = User.new(user_params)

		if user.save
			redirect_to user_path(user)
		else
			redirect_to new_user_path
		end

	end

	def destroy

	end

	def new
		@user = User.new
	end


	private

	def user_params
		params.require(:user).permit(:name, :email, :password)
	end
end

week 4/auction/app/helpers/application_helper.rb
module ApplicationHelper
end

week 4/auction/app/helpers/bids_helper.rb
module BidsHelper
end

week 4/auction/app/helpers/products_helper.rb
module ProductsHelper
end

week 4/auction/app/helpers/users_helper.rb
module UsersHelper
end

week 4/auction/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auction</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

week 4/auction/app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<h1>Register Today</h1>
	
	<%= form_for @user do |f| %>
		<%=f.label :name %>
		<%=f.text_field :name %>

		<%= f.label :email %>
		<%= f.text_field :email %>

		<%= f.label :password %>
		<%= f.password_field :password %>

		<%= f.button %>

	<%end%>
</body>
</html>	

week 4/auction/app/views/users/show.html.erb
<% if @products %>
	<ul>
		<% @products.each do |product| %>
			<li><%=product.title%></li> <%= link_to "See product", product_path(product) %>
		<%end%>
	</ul>
	<%= link_to "Add new product", new_user_product_path(@user) %>
<%end%> 

week 4/auction/app/views/users/welcome.html.erb
<h1>Welcome to ReBay</h1>


<form action="/login" method= "POST">
  	<div>
    	<input type = "text" name="email" placeholder="email"></textarea>
  	</div>
  	<div>
    	<input type = "password" name="password" placeholder="password"></textarea>
  	</div>
  	<div>
	  	<%if flash[:notice] %>
	  		<%= flash[:notice] %> 
	  	<% end %>
  	</div>
  	<button type="submit">Login</button>
  	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

</form>