week 4/language/config/routes.rb
Rails.application.routes.draw do
  
  root 'site#home'
  devise_for :admins
  get '/', to: 'site#home'
  get '/schools/admin/index', to: 'schools#admin_index'
  get '/school/delete/:id', to: 'schools#destroy',
   as: 'delete_school'

  resources :schools, only: [:show, :index, :create, :new, :edit, :update]

 

end

week 4/language/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

week 4/language/app/models/school.rb
class School < ActiveRecord::Base

	validates :name, presence: true, length: { maximum: 255 },
	                    uniqueness: { case_sensitive: false }
	
	has_attached_file :image, styles: {large: "600x600>", medium: "300x300>"}
  	
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  	

end

week 4/language/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

week 4/language/app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
	before_action :authenticate_admin!, only: [:admin_index, :edit, :create, :new]

	def index
		# def static_map_for(location, options = {})
  #   	params = {
	 #      :center => [location.lat, location.lon].join(","),
	 #      :zoom => 15,
	 #      :size => "300x300",
	 #      :markers => [location.lat, location.lon].join(","),
	 #      :sensor => true
	 #      }.merge(options)
		# 	query_string =  params.map{|k,v| "#{k}=#{v}"}.join("&")
	 #    	"http://maps.googleapis.com/maps/api/staticmap?#{query_string}"
	 #    	&markers=#{location.latitude}%2C#{location.longitude}
  # 		end

		@schools = School.all
		#@school.each do |school|
		#@url = static_map_for(school_map)
		
  	end
	def new
		@school = School.new
	end

	def create
		school = School.new(school_params)
		school.save
		redirect_to schools_admin_index_path
	end

	def admin_index
		@schools = School.all
	end

	def show
		@school = School.find(params[:id])
	end

	def edit
		@school = School.find(params[:id])
	end

	def destroy
		School.find(params[:id]).destroy
		redirect_to schools_admin_index_path
	end

	def update
		school = School.find(params[:id])
		if school.update(school_params)
			redirect_to schools_admin_index_path
		else
			redirect_to edit_school_path(school)
		end

	end


	
	private

	def school_params
		params.require(:school).permit(:name, :contact, :city, :price, :description, :lat, :lon, :image)
	end


end

week 4/language/app/controllers/site_controller.rb
class SiteController < ApplicationController

	def home

	end
	
end

week 4/language/app/helpers/application_helper.rb
module ApplicationHelper
end

week 4/language/app/helpers/schools_helper.rb
module SchoolsHelper
end

week 4/language/app/helpers/site_helper.rb
module SiteHelper
end

week 4/language/app/views/layouts/_header.html.erb
<header class="container header clearfix">
	<nav class="row navbar navbar-default navbar-fixed-top">
  		<div class="container col-md-5">
			<ul class="nav navbar-nav navbar-top-links">
				<li><a href='/'><span class="glyphicon glyphicon-home"></span> Home</a></li>
				<li><%= link_to '<span class="glyphicon glyphicon-education"></span> Schools'.html_safe, schools_path %></li>
				<li><a href="#"><span class="glyphicon glyphicon-pencil"></span> Blog</a></li>
				<% if admin_signed_in? %>
				   <li class=dropdown>
						<a class="dropdown-toggle" data-toggle="dropdown" href="">
						<span class="glyphicon glyphicon-wrench"></span> Admin Tools</a>
	                    <ul class="dropdown-menu">
				   			<li>
								<%= link_to '<span class="glyphicon glyphicon-education"></span> Edit Schools'.html_safe, schools_admin_index_path %>
	                        </li>
				   			<li>
					   			<%= link_to '<span class="glyphicon glyphicon-user"></span> Add Admin'.html_safe, new_admin_registration_path %>
	                        </li>
				   			<li>
					   			<a href="#">
	                               	Edit Schools
	                            </a>
	                        </li>
				   		</ul>
				   	</li>
				<%end%>
			</ul>
		</div>
				
		<div class="container col-md-2">
			<img src="assets/logo.png" class="img-responsive">
		</div>

		<div class="col-md-5">
			<ul class="nav navbar-nav pull-right">
				<%if current_admin %>
					<li style = "line-height: 50px; color: grey;"> <%=current_admin.email.split('@')[0] %> </li>
					<li><%= link_to '<span class="glyphicon glyphicon-user"></span> Log out'.html_safe, destroy_admin_session_path%></li>
				<%else%>
					<li><%= link_to '<span class="glyphicon glyphicon-user"></span> Admin'.html_safe, new_admin_session_path%></li>
				<%end%>
			</ul>
		</div>
	</nav>
</header>


<li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Page 1-1</a></li>
          <li><a href="#">Page 1-2</a></li>
          <li><a href="#">Page 1-3</a></li>
        </ul>
      </li>
 

week 4/language/app/views/layouts/_school_form.html.erb
<%= form_for @school, html: {multipart: true} do |f| %>
	
	<div class="field">
		<%=f.label :name %>
		<%=f.text_field :name %>
		<br>
	</div>

	<div class="field">
		<%=f.label :contact %>
		<%=f.text_field :contact %>
		<br>
	</div>

	<div class="field">
		<%=f.label :city %>
		<%=f.text_field :city %>
		<br>
	</div>
	
	<div class="field">
		<%=f.label :price %>
		<%=f.text_field :price %>
		<br>
	</div>

	<div class="field">
		<%=f.label :lat %>
		<%=f.text_field :lat %>
		<br>
	</div>

	<div class="field">
		<%=f.label :lon %>
		<%=f.text_field :lon %>
		<br>
	</div>

	<div class="field">
		<%=f.label :description %>
		<%=f.text_area :description %>
		<br>
	</div>

	<div class="field">
		<%=f.label :image %>
		<%=f.file_field :image %>
		<br>
	</div>
	<div class="actions">
		<%= f.button %>
	</div>
	
<%end%>

week 4/language/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Language</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  	
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
	<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
	<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

  
</head>
<body>


<%= yield %>

</body>
</html>

week 4/language/app/views/schools/admin_index.html.erb
<%= render :partial => '/layouts/header' %>

<div class="container-fluid", style="margin-top: 100px">
	<div class="row">
		<div class="col-sm-2"></div>
		<div class="col-sm-8">
			<table class="table table-striped">
			    <thead>
			      	<tr>
				        <th>Name</th>
				        <th>City</th>
				        <th>Contact</th>
				        <th>Price</th>
				        <th></th>
				        <th></th>
				        <th></th>
			      	</tr>
			    </thead>
			    <tbody>
				    <% @schools.each do |school| %>
				    <tr>
				    	<td><%=school.name%></td>
				    	<td><%=school.city%></td>
				    	<td><%=school.contact%></td>
				    	<td>€<%=school.price.to_i%></td>
				    	<td>
				    		<%= link_to '<button type="button" class="btn btn-success">View</button>'.html_safe, school_path(school)%>
				    	</td>
				    	<td>
							<%= link_to '<button type="button" class="btn btn-primary">Edit</button>'.html_safe, edit_school_path(school)%>
				    	</td>
				    	<td>
				    		<a href="/school/delete/<%=school.id%>" method="DELETE" data-confirm= "Are you sure"><button type="button" class="btn btn-danger">Delete</button></a>
				    	</td>
				    </tr>
				    <%end%>
				</tbody>
			  </table>
			  <%= link_to '<button type="button" class="btn btn-success">Add new School </button>'.html_safe, new_school_path%>
			  

		</div>
		<div class="col-sm-2"></div>
	</div>
</div>

week 4/language/app/views/schools/edit.html.erb
<%= render :partial => '/layouts/school_form' %>

week 4/language/app/views/schools/index.html.erb
<%= render :partial => '/layouts/header' %>


<div class="container-fluid" style='margin-top: 50px;'>
	
	<div class="row">
	<div class="column col-sm-2 sidebar" id="sidebar">
        <ul class="nav">
            <% @schools.each do |school| %>
            	<li><a href="#<%=school.id%>" class = "list-group-item"><%=school.name%></a></li>
            <%end%>
        </ul>
    </div>
	
	<div class="col-sm-3">
		
	</div>
	
	<div class="col-sm-6">
		<!-- <img src="<%=@url%>" alt=""> -->
		
		<ul class="school_index">
		    <% @schools.each do |school| %>
		        <span class="anchor" id="<%=school.id%>"></span>
			    <div>
			        <%=school.name%><br>
			       	<hr>
			        <%=school.description%><br>
			    	<hr>
			    	<%=image_tag school.image.url(:large) %><br>
		    	</div>
			<%end%>
		</ul>
	</div>

	<div class="col-sm-5"></div>

</div>
</div>


<script>
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
</script>

week 4/language/app/views/schools/new.html.erb
<%= render :partial => '/layouts/school_form' %>

week 4/language/app/views/schools/show.html.erb
<%=image_tag @school.image.url(:large) %>